apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meow-application.fullname" . }}-deployment
  labels:
    {{- include "meow-application.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  selector:
    matchLabels:
      {{- include "meow-application.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "meow-application.labels" . | nindent 8 }}
    spec:
      containers:
        - name: meow-container
          image: {{ .Values.image.repository }}
          ports:
            - name: {{ .Values.service.port }}
              containerPort: 8080
          env:
            - name: DO_YOU_LIKE_CATS
              value: "yes"
            - name: CATS_URL
              value: "http://cat-service:8080/cats"
          readinessProbe:
            httpGet:
              path: /meow
              port: {{ .Values.service.port }}
