apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "meow-application.name" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.pod.path }}
            backend:
              serviceName: {{ include "meow-application.name" . }}-service
              servicePort: {{ .Values.service.port }}
