apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: meow-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  backend:
    serviceName: meow-service
    servicePort: 80
