apiVersion: v1
kind: Service
metadata:
  name: meow-service
spec:
  type: NodePort
  selector: {{- include "meow-application.labels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
