apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cat-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: a6234ccf43e6f11eab63c024d2ff4f4a-597942603.us-west-2.elb.amazonaws.com
      http:
        paths:
          - path: /cats
            backend:
              serviceName: cat-service
              servicePort: 8080
