apiVersion: v1
kind: Pod
metadata:
  name: meow-pod
  labels:
    type: meow
spec:
  containers:
    - name: meow-container
      image: janesee3/meow-application:1
      env:
        - name: DO_YOU_LIKE_CATS
          value: "yes"
